web_http:
  ip: "0.0.0.0"
  port: 8080
  
docker_hub:
  username: "name"
  password: "dckr_pat_fYrK7Smu5xx"

github:
  username: "name"
  token: "ghp_vcmnfoS75jweJxxxxxx"

gitea:
  username: "name"  
  token: ""

proxy:
  enabled: false
  http: "http://192.168.100.3:2080"
  https: "http://192.168.100.3:2080"
  no_proxy: "localhost,127.0.0.1"
notify:
    ntfy:
        enabled: true
        url: https://ntfy.cn
        topic: docker-build
        token: tk_zeebvxsp8dnqruxxxxxx
    dingtalk:
        enabled: false
        webhook: https://oapi.dingtalk.com/robot/send?access_token=6b56f336821992a7033321d6d521111111xxxxxxxxxx
        client_id: dingvte8dxxxxxxx
        client_secret: d6Vg0cNHApuS__xxxxxxx73q
repositories:
  - url: "https://github.com/sipeed/picoclaw" #仓库地址，目前只支持Github仓库
    name_task: "picoclaw"
    enabled: false #是否启用构建，默认false
    auth: "github" #认证方式，默认github
    tag_branch: "main" #指定tag或branch
    tag_docker: "latest" #镜像版本
    dockerfile_project: "docker/Dockerfile" #git clone 项目中Dockerfile相对路径，默认为根目录下Dockerfile
    dockerfile_user: "" #构建镜像时会从指定位置复制Dockerfile文件到目标项目根目录。dockerfile_user优先级高dockerfile_project 如:dockerfile/hello/Dockerfile，会将hello识别为镜像主名称
    platforms: #默认：linux/amd64
      - "linux/amd64"
      - "linux/arm64"
    build_args: #从Dockerfile中传弟参数
      VERSION: "1.0.0"
      BUILD_DATE: "2026-03-12"
  - url: ""
    enabled: true
    tag_branch: "master"
    tag_docker: "latest"
    dockerfile_user: "dockerfile/go-thrift/Dockerfile"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    build_args:
      THRIFT_VERSION: "latest"           
